### ISSUE TITLE
Update readme and p!help commands

### ISSUE THREAD

**Issue by pianiststickman** [ubermadness/Pinano-Discord-Bot#22]

**Comment by Juliacare** [comment]
What do you want it updated to?

**Comment by pianiststickman** [comment]
Just the current usage. p!stats is runnable on other users now.

The README could be updated to a new user start-up guide - should explain all the steps in checking out the code, installing node, necessary packages, how to self-host and bring the bot to the server, how to run the tests, etc.

**Comment by Juliacare** [comment]
The readme stuff seems more like a wiki page. But I'll rewrite help after im back from the store.

**Comment by Juliacare** [comment]
Done in https://github.com/ubermadness/Pinano-Discord-Bot/commit/d1f2b37065668ff9a9f90a8f255ec2c14623bed6
